%% setup
test_folder = fileparts( mfilename( 'fullpath' ) );
stl_file = fullfile( test_folder, 'base_plate.stl' );
settings_file = which( 'oo_settings.json' );
output_folder = fullfile( test_folder, 'output' );

%% base case
obc_path = generate_base_case_data( ...
    settings_file, ...
    stl_file, ...
    output_folder ...
    );

%% trial case
objective_variables_file = which( 'objective_variables.json' );
ANGLES = [ pi 0.87266 ];
SLURM_ARRAY_JOB_ID = 1;
SLURM_JOB_ID = 314159;
generate_csvs_on_hpc( ...
    obc_path, ...
    objective_variables_file, ...
    ANGLES, ...
    SLURM_ARRAY_JOB_ID, ...
    SLURM_JOB_ID, ...
    output_folder ...
    );

