classdef ButtonOption < ThresholdingOption
    
    methods ( Access = public )
        
        function obj = ButtonOption( ...
                button_group_handle, ...
                id, ...
                value_picker_fn, ...
                y_pos, ...
                font_size, ...
                radio_button_label, ...
                push_button_label, ...
                push_button_pressed_callback ...
                )
            
            obj = obj@ThresholdingOption( ...
                button_group_handle, ...
                id, ...
                value_picker_fn, ...
                y_pos, ...
                font_size, ...
                radio_button_label ...
                );
            obj.push_button_handle = obj.prepare_push_button( ...
                button_group_handle, ...
                y_pos, ...
                font_size, ...
                push_button_label, ...
                @(h,e)push_button_pressed_callback(h,e,obj) ...
                );
            
        end
        
    end
    
    
    methods ( Access = public, Static )
        
        function type = get_type()
            
            type = 'button';
            
        end
        
    end
    
    
    properties ( Access = private )
        
        push_button_handle
        
    end
    
    
    % construction
    methods ( Access = private )
        
        function h = prepare_push_button( ...
                obj, ...
                button_group_handle, ...
                y_pos, ...
                font_size, ...
                label, ...
                button_callback ...
                )
            
            h = uicontrol();
            h.Style = 'pushbutton';
            h.String = label;
            h.FontSize = font_size;
            h.Position = [ ...
                obj.get_edit_text_x_pos() ...
                y_pos ...
                obj.EDIT_TEXT_WIDTH ...
                get_height( font_size ) ...
                ];
            h.Parent = button_group_handle;
            h.Callback = button_callback;
            
        end
        
    end
    
end

