function generate_csvs_on_hpc( ...
    component_path, ...
    feeders_path, ...
    option_path, ...
    objective_variables_path, ...
    angles, ...
    slurm_array_job_id, ...
    slurm_job_id, ...
    output_folder, ...
    var_add_paths ...
    )

if nargin >= 9
    original_path = [];
    for i = 1 : numel( var_add_paths )
        oldpath = addpath( genpath( var_add_paths{ i } ) );
        if i == 1
            original_path = oldpath;
        end
    end
    cleanup = onCleanup( @()path(original_path) );
end

opt = OrientationBaseCase( ...
    component_path, ...
    feeders_path, ...
    option_path, ...
    objective_variables_path ...
    );

results = opt.determine_results_as_table( angles );

filename = sprintf( ...
    'results_%s_%i_%i.csv', ...
    opt.get_name(), ...
    slurm_job_id, ...
    slurm_array_job_id ...
    );
writetable( results, fullfile( output_folder, filename ) );

end