function generate_csvs_on_hpc( ...
    base_case_file, ...
    objectives_file, ...
    angles, ...
    slurm_array_job_id, ...
    slurm_job_id, ...
    output_folder ...
    )

obc = OrientationBaseCase.load_obj( base_case_file );
ov = ObjectiveVariables( objectives_file, obc );
dv = DecisionVariables( angles );
results = ov.evaluate( dv );

results_file = sprintf( ...
    'results_%s_%i_%i.csv', ...
    obc.name, ...
    slurm_job_id, ...
    slurm_array_job_id ...
    );
writetable( results, fullfile( output_folder, results_file ) );

end