function results_file = generate_csvs_on_hpc( ...
    base_case_file, ...
    recipe_class, ...
    angles, ...
    slurm_array_job_id, ...
    slurm_job_id, ...
    output_folder ...
    )

obc = OrientationBaseCase.load_obj( base_case_file );
recipe = str2func( recipe_class );
recipe = recipe();
assert( isa( recipe, "OrientationRecipeInterface" ) );
data = recipe.evaluate( obc, angles );
results_file = sprintf( ...
    "results_%s_%i_%i.mat", ...
    obc.name, ...
    slurm_job_id, ...
    slurm_array_job_id ...
    );
results_file = fullfile( output_folder, results_file );
data.save_obj( results_file );

end