%% setup
test_folder = fileparts( mfilename( 'fullpath' ) );
stl_file = fullfile( test_folder, 'base_plate.stl' );
settings_file = which( 'extraction_settings.json' );
output_folder = fullfile( test_folder, 'output' );

%% base case
obc_file = generate_base_case_data( ...
    settings_file, ...
    stl_file, ...
    output_folder ...
    );

%% trial case
ANGLES = [ pi 0.87266 ];
SLURM_ARRAY_JOB_ID = 1;
SLURM_JOB_ID = 314159;
first_file = generate_data_on_hpc( ...
    obc_file, ...
    "DefaultRecipe", ...
    ANGLES, ...
    SLURM_ARRAY_JOB_ID, ...
    SLURM_JOB_ID, ...
    output_folder ...
    );

%% second and third case
ANGLES = [ 0 0 ];
SLURM_ARRAY_JOB_ID = 2;
second_file = generate_data_on_hpc( ...
    obc_file, ...
    "DefaultRecipe", ...
    ANGLES, ...
    SLURM_ARRAY_JOB_ID, ...
    SLURM_JOB_ID, ...
    output_folder ...
    );

ANGLES = [ 1 1 ];
SLURM_ARRAY_JOB_ID = 3;
third_file = generate_data_on_hpc( ...
    obc_file, ...
    "DefaultRecipe", ...
    ANGLES, ...
    SLURM_ARRAY_JOB_ID, ...
    SLURM_JOB_ID, ...
    output_folder ...
    );

%% load and merge
lhs = OrientationData.load_obj( first_file );
rhs( 1 ) = OrientationData.load_obj( second_file );
rhs( 2 ) = OrientationData.load_obj( third_file );
all = lhs.merge( rhs );
