classdef QuantileOption < ValueOption
    
    methods ( Access = public )
        
        function obj = QuantileOption( ...
                button_group_handle, ...
                id, ...
                value_picker_fn, ...
                y_pos, ...
                font_size, ...
                label, ...
                value_changed_callback ...
                )
            
            obj = obj@ValueOption( ...
                button_group_handle, ...
                id, ...
                value_picker_fn, ...
                y_pos, ...
                font_size, ...
                label, ...
                value_changed_callback ...
                );
            
        end
        
        
        function set_range( obj, ~ )
            
            range.min = 0;
            range.max = 1;
            obj.set_threshold_value_range( range );
            obj.set_handle_ranges( range );
            obj.update_handle_values( obj.get_threshold_value() );
            
        end
        
    end
    
    
    methods ( Access = public, Static )
        
        function type = get_type()
            
            type = 'quantile';
            
        end
        
    end
    
end

